version: '3.8'

services:
  nextjs:
    build:
      context: ../../../Downloads/project-bolt-sb1-u7rtn5/project
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  nginx:
    build:
      context: ../../../Downloads/project-bolt-sb1-u7rtn5/project
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge